linters:
  # JavaScript
  - eslint --ignore-path .gitignore .
  - jshint . --verbose

  # YAML
  - yamllint -c yamllint.yml .

  # Markdown
  - proselint *.md
  - remark *.md --quiet --frail --no-stdout
  - write-good *.md || true

  # CSS
  - scss-lint test/fixture/*.css
  - sass-lint test/fixture/*.css
  - csslint test/fixture/*.css
  - stylelint test/fixture/*.css
  - doiuse test/fixture/*.css

  # Shell colors
  - sh test/colors.sh

  # Dockerfile
  - dockerfile_lint -f Dockerfile
